-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying NOT NULL,
    web_sites character varying NOT NULL,
    phone character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    position_name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    national_id bigint NOT NULL,
    birth_of_date date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.system_users
(
    userid integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    PRIMARY KEY (userid)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(40) NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_status
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    email_verification boolean,
    system_verification boolean,
    mernis_verification boolean,
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_users
    ADD FOREIGN KEY (userid)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.verification_status
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;

END;
